name: SkyKits
version: 1.9.6
main: me.douglasamv.kitpvp.Main
author: DouglasDev
commands:
   build:
   score:
   check:
   rank:
   tag:
   lag:
   set:
   cc:
   chat:
   spawn:
   admin:
   sc:
   staffchat:
   report:
   gm:
   invsee:
   tpall:
   fly:
   tp:
   s:
   pvp:
   1v1:
   money:
   resetkdr: