name: MultiFerramenta
main: rush.multiferramenta.Main
author: RUSH
version: 1.0

commands:
  givemulti:
    description: Giva uma multi ferramenta.
    permission: multi.cmd
    permission-message: "§cVocê não tem permissão para utilizar este comando."