## Plugin by LeitinhooowEz ##
## Todos direitos reservados ##
## WomboLobby 1.0 Replica ##

# CONFIGURAVEL
Loja: 'loja.wombocraft.com.br'
Nome_Scoreboard: '&e&l  WOMBOCRAFT'
Prefix: '&e&lWOMBOCRAFT '