package bLoja.Main;

import java.util.*;

public class NomeItens
{
    public static HashMap<Integer, String> nomes;
    
    static {
        NomeItens.nomes = new HashMap<Integer, String>();
    }
    
    public static void carregarNomes() {
        NomeItens.nomes.put(1, "Pedra lisa");
        NomeItens.nomes.put(2, "Bloco de Grama");
        NomeItens.nomes.put(3, "Terra");
        NomeItens.nomes.put(4, "Pedra");
        NomeItens.nomes.put(5, "Madeira");
        NomeItens.nomes.put(6, "Muda");
        NomeItens.nomes.put(7, "Rocha matriz");
        NomeItens.nomes.put(8, "Agua");
        NomeItens.nomes.put(9, "Agua");
        NomeItens.nomes.put(10, "Lava");
        NomeItens.nomes.put(11, "Lava");
        NomeItens.nomes.put(12, "Areia");
        NomeItens.nomes.put(13, "Cascalho");
        NomeItens.nomes.put(14, "Min\u00e9rio de Ouro");
        NomeItens.nomes.put(15, "Min\u00e9rio de Ferro");
        NomeItens.nomes.put(16, "Min\u00e9rio de Carv\u00e3o");
        NomeItens.nomes.put(17, "Madeira Bruta");
        NomeItens.nomes.put(18, "Folhas");
        NomeItens.nomes.put(19, "Esponja");
        NomeItens.nomes.put(20, "Vidro");
        NomeItens.nomes.put(21, "Min\u00e9rio de L\u00e1pis");
        NomeItens.nomes.put(22, "Bloco de L\u00e1pis");
        NomeItens.nomes.put(23, "Ejetor");
        NomeItens.nomes.put(24, "Arenito");
        NomeItens.nomes.put(25, "Bloco de nota");
        NomeItens.nomes.put(26, "Cama");
        NomeItens.nomes.put(27, "Trilho El\u00e9trico");
        NomeItens.nomes.put(28, "Trilho Detector");
        NomeItens.nomes.put(29, "Pist\u00e3o grudento");
        NomeItens.nomes.put(30, "Teia");
        NomeItens.nomes.put(31, "Grama");
        NomeItens.nomes.put(32, "Arbusto Morto");
        NomeItens.nomes.put(33, "Pist\u00e3o");
        NomeItens.nomes.put(34, "Pist\u00e3o Ativo");
        NomeItens.nomes.put(35, "L\u00e3");
        NomeItens.nomes.put(37, "Dende-de-Le\u00e3o");
        NomeItens.nomes.put(38, "Papoula");
        NomeItens.nomes.put(39, "Cogumelo");
        NomeItens.nomes.put(40, "Cogumelo Vermelho");
        NomeItens.nomes.put(41, "Bloco de Ouro");
        NomeItens.nomes.put(42, "Bloco de Ferro");
        NomeItens.nomes.put(44, "Laje");
        NomeItens.nomes.put(45, "Tijolos");
        NomeItens.nomes.put(46, "Dinamite");
        NomeItens.nomes.put(47, "Estante");
        NomeItens.nomes.put(48, "Pedra com Musgo");
        NomeItens.nomes.put(49, "Obsidiana");
        NomeItens.nomes.put(50, "Tocha");
        NomeItens.nomes.put(52, "Gerador de Monstros");
        NomeItens.nomes.put(53, "Escada de Carvalho");
        NomeItens.nomes.put(54, "Ba\u00fa");
        NomeItens.nomes.put(56, "Min\u00e9rio de Diamante");
        NomeItens.nomes.put(57, "Bloco de Diamante");
        NomeItens.nomes.put(58, "Mesa de Trabalho");
        NomeItens.nomes.put(61, "Fornalha");
        NomeItens.nomes.put(65, "Escada");
        NomeItens.nomes.put(66, "Trilho");
        NomeItens.nomes.put(67, "Escada de Pedra");
        NomeItens.nomes.put(69, "Alavanca");
        NomeItens.nomes.put(70, "Placa de Press\u00e3o");
        NomeItens.nomes.put(72, "Placa de press\u00e3o");
        NomeItens.nomes.put(73, "Min\u00e9rio de Redstone");
        NomeItens.nomes.put(76, "Tocha de Redstone");
        NomeItens.nomes.put(77, "Bot\u00e3o");
        NomeItens.nomes.put(78, "Neve");
        NomeItens.nomes.put(79, "Gelo");
        NomeItens.nomes.put(80, "Bloco de Neve");
        NomeItens.nomes.put(81, "Cacto");
        NomeItens.nomes.put(82, "Argila");
        NomeItens.nomes.put(84, "Jukebox");
        NomeItens.nomes.put(85, "Cerca de Carvalho");
        NomeItens.nomes.put(86, "Ab\u00f3bora");
        NomeItens.nomes.put(87, "Rocha do Nether");
        NomeItens.nomes.put(88, "Areia das Almas");
        NomeItens.nomes.put(89, "Pedra Luminosa");
        NomeItens.nomes.put(90, "Portal");
        NomeItens.nomes.put(91, "Ab\u00f3bora Acesa");
        NomeItens.nomes.put(95, "Vidro Tingido");
        NomeItens.nomes.put(96, "Al\u00e7ap\u00e3o de Madeira");
        NomeItens.nomes.put(97, "Ovo de Monstro");
        NomeItens.nomes.put(98, "Tijolos de Pedra");
        NomeItens.nomes.put(101, "Barras de Ferro");
        NomeItens.nomes.put(102, "Painel de Vidro");
        NomeItens.nomes.put(103, "Melancia");
        NomeItens.nomes.put(106, "Vinhas");
        NomeItens.nomes.put(107, "Port\u00e3o de Carvalho");
        NomeItens.nomes.put(108, "Escadas de Tijolos");
        NomeItens.nomes.put(109, "Escadas de Pedra");
        NomeItens.nomes.put(110, "Mic\u00e9lio");
        NomeItens.nomes.put(111, "Vit\u00f3ria-R\u00e9gia");
        NomeItens.nomes.put(112, "Tijolos do Nether");
        NomeItens.nomes.put(113, "Cerca de Tijolos");
        NomeItens.nomes.put(114, "Escada do Nether");
        NomeItens.nomes.put(116, "Mesa de Encantamentos");
        NomeItens.nomes.put(121, "Pedra do Fim");
        NomeItens.nomes.put(122, "Ovo do Drag\u00e3o");
        NomeItens.nomes.put(123, "L\u00e2mpada de Redstone");
        NomeItens.nomes.put(126, "Laje de Madeira");
        NomeItens.nomes.put(128, "Escada de Arenito");
        NomeItens.nomes.put(129, "Min\u00e9rio de Esmeralda");
        NomeItens.nomes.put(130, "Ba\u00fa do Fim");
        NomeItens.nomes.put(131, "Gancho de Armadilha");
        NomeItens.nomes.put(133, "Bloco de Esmeralda");
        NomeItens.nomes.put(134, "Escadas de Pinheiro");
        NomeItens.nomes.put(135, "Escadas de Eucalipto");
        NomeItens.nomes.put(136, "Escada da Selva");
        NomeItens.nomes.put(137, "Bloco de Comando");
        NomeItens.nomes.put(138, "Sinalizador");
        NomeItens.nomes.put(139, "Parede de Pedregulho");
        NomeItens.nomes.put(143, "Bot\u00e3o");
        NomeItens.nomes.put(145, "Bigorna");
        NomeItens.nomes.put(146, "Ba\u00fa com Armadilha");
        NomeItens.nomes.put(147, "Placa de Press\u00e3o");
        NomeItens.nomes.put(148, "Placa de Press\u00e3o");
        NomeItens.nomes.put(151, "Sensor de Luz");
        NomeItens.nomes.put(152, "Bloco de Redstone");
        NomeItens.nomes.put(153, "Min\u00e9rio de Quartzo");
        NomeItens.nomes.put(154, "Funil");
        NomeItens.nomes.put(155, "Bloco de Quartzo");
        NomeItens.nomes.put(156, "Escadas de Quartzo");
        NomeItens.nomes.put(157, "Trilho Ativador");
        NomeItens.nomes.put(158, "Liberador");
        NomeItens.nomes.put(159, "Argila");
        NomeItens.nomes.put(160, "Painle de Vidro");
        NomeItens.nomes.put(161, "Folhas");
        NomeItens.nomes.put(162, "Madeira Bruta");
        NomeItens.nomes.put(163, "Escadas de Ac\u00e1cia");
        NomeItens.nomes.put(164, "Escadas Escura");
        NomeItens.nomes.put(165, "Bloco de Slime");
        NomeItens.nomes.put(166, "Barreira");
        NomeItens.nomes.put(167, "Al\u00e7ap\u00e3o de Ferro");
        NomeItens.nomes.put(168, "Prismarinho");
        NomeItens.nomes.put(169, "Lanterna do Mar");
        NomeItens.nomes.put(170, "Fardo de Feno");
        NomeItens.nomes.put(171, "Carpete");
        NomeItens.nomes.put(172, "Argila Endurecida");
        NomeItens.nomes.put(173, "Bloco de Carv\u00e3o");
        NomeItens.nomes.put(174, "Gelo Compactado");
        NomeItens.nomes.put(175, "Flor");
        NomeItens.nomes.put(179, "Arenito Vermelho");
        NomeItens.nomes.put(180, "Escadas Vermelhas");
        NomeItens.nomes.put(182, "Laje Vermelha");
        NomeItens.nomes.put(183, "Port\u00e3o de Pinheiro");
        NomeItens.nomes.put(184, "Port\u00e3o de Eucalipto");
        NomeItens.nomes.put(185, "Port\u00e3o da Selva");
        NomeItens.nomes.put(186, "Port\u00e3o Escuro");
        NomeItens.nomes.put(187, "Port\u00e3o de Ac\u00e1cia");
        NomeItens.nomes.put(188, "Cerca de Pinheiro");
        NomeItens.nomes.put(189, "Cerca de Eucalipto");
        NomeItens.nomes.put(190, "Cerca da Selva");
        NomeItens.nomes.put(191, "Cerca Escura");
        NomeItens.nomes.put(192, "Cerca de Ac\u00e1cia");
        NomeItens.nomes.put(256, "P\u00e1 de Ferro");
        NomeItens.nomes.put(257, "Picareta de Ferro");
        NomeItens.nomes.put(258, "Machado de Ferro");
        NomeItens.nomes.put(259, "Isqueiro");
        NomeItens.nomes.put(260, "Ma\u00e7\u00e3");
        NomeItens.nomes.put(261, "Arco");
        NomeItens.nomes.put(262, "Flecha");
        NomeItens.nomes.put(263, "Carv\u00e3o");
        NomeItens.nomes.put(264, "Diamante");
        NomeItens.nomes.put(265, "Barra de Ferro");
        NomeItens.nomes.put(266, "Barra de Ouro");
        NomeItens.nomes.put(267, "Espada de Ferro");
        NomeItens.nomes.put(268, "Espada de Madeira");
        NomeItens.nomes.put(269, "P\u00e1 de Madeira");
        NomeItens.nomes.put(270, "Picareta de Madeira");
        NomeItens.nomes.put(271, "Machado de Madeira");
        NomeItens.nomes.put(272, "Espada de Pedra");
        NomeItens.nomes.put(273, "P\u00e1 de Pedra");
        NomeItens.nomes.put(274, "Picareta de Pedra");
        NomeItens.nomes.put(275, "Machado de Pedra");
        NomeItens.nomes.put(276, "Espada de Diamante");
        NomeItens.nomes.put(277, "P\u00e1 de Diamante");
        NomeItens.nomes.put(278, "Picareta de Diamante");
        NomeItens.nomes.put(279, "Machado de Diamante");
        NomeItens.nomes.put(280, "Graveto");
        NomeItens.nomes.put(281, "Tigela");
        NomeItens.nomes.put(282, "Ensopado");
        NomeItens.nomes.put(283, "Espada de Ouro");
        NomeItens.nomes.put(284, "P\u00e1 de Ouro");
        NomeItens.nomes.put(285, "Picareta de Ouro");
        NomeItens.nomes.put(286, "Machado de Ouro");
        NomeItens.nomes.put(287, "Linha");
        NomeItens.nomes.put(288, "Pena");
        NomeItens.nomes.put(289, "P\u00f3lvora");
        NomeItens.nomes.put(290, "Enxada de Madeira");
        NomeItens.nomes.put(291, "Enxada de Pedra");
        NomeItens.nomes.put(292, "Enxada de Ferro");
        NomeItens.nomes.put(293, "Enxada de Diamante");
        NomeItens.nomes.put(294, "Enxada de Ouro");
        NomeItens.nomes.put(295, "Sementes");
        NomeItens.nomes.put(296, "Trigo");
        NomeItens.nomes.put(297, "P\u00e3o");
        NomeItens.nomes.put(298, "Capuz de Couro");
        NomeItens.nomes.put(299, "T\u00fanica de Couro");
        NomeItens.nomes.put(300, "Cal\u00e7as de Couro");
        NomeItens.nomes.put(301, "Botas de Couro");
        NomeItens.nomes.put(302, "Coifa de Malha");
        NomeItens.nomes.put(303, "Peitoral de Malha");
        NomeItens.nomes.put(304, "Cal\u00e7a de Malha");
        NomeItens.nomes.put(305, "Botas de Malha");
        NomeItens.nomes.put(306, "Elmo de Ferro");
        NomeItens.nomes.put(307, "Peitoral de Ferro");
        NomeItens.nomes.put(308, "Cal\u00e7as de Ferro");
        NomeItens.nomes.put(309, "Botas de Ferro");
        NomeItens.nomes.put(310, "Elmo de Diamante");
        NomeItens.nomes.put(311, "Peitoral de Diamante");
        NomeItens.nomes.put(312, "Cal\u00e7as de Diamante");
        NomeItens.nomes.put(313, "Botas de Diamante");
        NomeItens.nomes.put(314, "Elmo de Ouro");
        NomeItens.nomes.put(315, "Peitoral de Ouro");
        NomeItens.nomes.put(316, "Cal\u00e7as de Ouro");
        NomeItens.nomes.put(317, "Botas de Ouro");
        NomeItens.nomes.put(318, "Perdeneira");
        NomeItens.nomes.put(319, "Porco Cr\u00fa");
        NomeItens.nomes.put(320, "Porco Assado");
        NomeItens.nomes.put(321, "Pintura");
        NomeItens.nomes.put(322, "Ma\u00e7\u00e3 Dourada");
        NomeItens.nomes.put(323, "Placa");
        NomeItens.nomes.put(324, "Porta de Carvalho");
        NomeItens.nomes.put(325, "Balde");
        NomeItens.nomes.put(326, "Balde de \u00c1gua");
        NomeItens.nomes.put(327, "Balde de Lava");
        NomeItens.nomes.put(328, "Carrinho");
        NomeItens.nomes.put(329, "Sela");
        NomeItens.nomes.put(330, "Porta de Ferro");
        NomeItens.nomes.put(331, "Redstone");
        NomeItens.nomes.put(332, "Bola de Neve");
        NomeItens.nomes.put(333, "Bote");
        NomeItens.nomes.put(334, "Couro");
        NomeItens.nomes.put(335, "Leite");
        NomeItens.nomes.put(336, "Tijolo");
        NomeItens.nomes.put(337, "Argila");
        NomeItens.nomes.put(338, "Canas-de-A\u00e7\u00facar");
        NomeItens.nomes.put(339, "Papel");
        NomeItens.nomes.put(340, "Livro");
        NomeItens.nomes.put(341, "Gosma de Slime");
        NomeItens.nomes.put(342, "Carrinho com Ba\u00fa");
        NomeItens.nomes.put(343, "Carrinho com Fornalha");
        NomeItens.nomes.put(344, "Ovo");
        NomeItens.nomes.put(345, "B\u00fassola");
        NomeItens.nomes.put(346, "Vara de Pescar");
        NomeItens.nomes.put(347, "Rel\u00f3gio");
        NomeItens.nomes.put(348, "P\u00f3 de Pedra");
        NomeItens.nomes.put(349, "Peixe");
        NomeItens.nomes.put(350, "Peixe Assado");
        NomeItens.nomes.put(351, "Corante");
        NomeItens.nomes.put(352, "Osso");
        NomeItens.nomes.put(353, "A\u00e7ucar");
        NomeItens.nomes.put(354, "Bolo");
        NomeItens.nomes.put(355, "Cama");
        NomeItens.nomes.put(356, "Repetidor de Redstone");
        NomeItens.nomes.put(357, "Biscoito");
        NomeItens.nomes.put(358, "Mapa");
        NomeItens.nomes.put(359, "Tesoura");
        NomeItens.nomes.put(360, "Melancia");
        NomeItens.nomes.put(361, "Semente de Ab\u00f3bora");
        NomeItens.nomes.put(362, "Semente de Melancia");
        NomeItens.nomes.put(363, "Bife Cru");
        NomeItens.nomes.put(364, "Fil\u00e9");
        NomeItens.nomes.put(365, "Frango Cru");
        NomeItens.nomes.put(366, "Frango Assado");
        NomeItens.nomes.put(367, "Carne Podre");
        NomeItens.nomes.put(368, "P\u00e9rola do Fim");
        NomeItens.nomes.put(369, "Vara de Blaze");
        NomeItens.nomes.put(370, "L\u00e1grima de Ghast");
        NomeItens.nomes.put(371, "Pepita de Ouro");
        NomeItens.nomes.put(372, "Fungo do Nether");
        NomeItens.nomes.put(373, "Po\u00e7\u00e3o");
        NomeItens.nomes.put(374, "Frasco de Vidro");
        NomeItens.nomes.put(375, "Olho de Aranha");
        NomeItens.nomes.put(376, "Olho de Aranha Fermentado");
        NomeItens.nomes.put(377, "P\u00f3 de Blaze");
        NomeItens.nomes.put(378, "Creme de Magma");
        NomeItens.nomes.put(379, "Suporte de Po\u00e7\u00f5es");
        NomeItens.nomes.put(380, "Caldeir\u00e3o");
        NomeItens.nomes.put(381, "Olho do Fim");
        NomeItens.nomes.put(382, "Melancia Reluzente");
        NomeItens.nomes.put(383, "Invocador");
        NomeItens.nomes.put(384, "Frasco de Encantamentos");
        NomeItens.nomes.put(385, "Bola de Fogo");
        NomeItens.nomes.put(386, "Pena e Livro");
        NomeItens.nomes.put(387, "Livro Escrito");
        NomeItens.nomes.put(388, "Esmeralda");
        NomeItens.nomes.put(389, "Moldura");
        NomeItens.nomes.put(390, "Vaso de Flor");
        NomeItens.nomes.put(391, "Cenoura");
        NomeItens.nomes.put(392, "Batata");
        NomeItens.nomes.put(393, "Batata Assada");
        NomeItens.nomes.put(394, "Batata Venenosa");
        NomeItens.nomes.put(395, "Mapa em Branco");
        NomeItens.nomes.put(396, "Cenoura Dourada");
        NomeItens.nomes.put(397, "Cabe\u00e7a");
        NomeItens.nomes.put(398, "Cenoura no Palito");
        NomeItens.nomes.put(399, "Estrela do Nether");
        NomeItens.nomes.put(400, "Torta de Ab\u00f3bora");
        NomeItens.nomes.put(401, "Fogos de Artif\u00edcio");
        NomeItens.nomes.put(402, "Estrela de Fogos");
        NomeItens.nomes.put(403, "Livro Encantado");
        NomeItens.nomes.put(404, "Comparador");
        NomeItens.nomes.put(405, "Tijolo do Nether");
        NomeItens.nomes.put(406, "Quartzo do Nether");
        NomeItens.nomes.put(407, "Carrinho com Dinamite");
        NomeItens.nomes.put(408, "Carrinho com Funil");
        NomeItens.nomes.put(409, "Fragmento de Prismarinho");
        NomeItens.nomes.put(410, "Cristais de Prismarinho");
        NomeItens.nomes.put(411, "Coelho Cru");
        NomeItens.nomes.put(412, "Coelho Assado");
        NomeItens.nomes.put(413, "Ensopado de Coelho");
        NomeItens.nomes.put(414, "P\u00e9 de Coelho");
        NomeItens.nomes.put(415, "Pelo de Coelho");
        NomeItens.nomes.put(416, "Suporte de Armaduras");
        NomeItens.nomes.put(417, "Armadura de Cavalo");
        NomeItens.nomes.put(418, "Armadura de Cavalo");
        NomeItens.nomes.put(419, "Armadura de Cavalo");
        NomeItens.nomes.put(420, "La\u00e7o");
        NomeItens.nomes.put(421, "Etiqueta");
        NomeItens.nomes.put(423, "Carneiro Cru");
        NomeItens.nomes.put(424, "Carneiro Assado");
        NomeItens.nomes.put(425, "Estandarte");
        NomeItens.nomes.put(427, "Porta de Pinheiro");
        NomeItens.nomes.put(428, "Porta de Eucalipto");
        NomeItens.nomes.put(429, "Porta da Selva");
        NomeItens.nomes.put(430, "Porta de Ac\u00e1cia");
        NomeItens.nomes.put(431, "Porta Escura");
        NomeItens.nomes.put(2256, "Disco de M\u00fasica");
    }
}
